<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.0 INSTALLER - Friday 28th of September 2012 10:35:14 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://www.gamerotor.com/php/hybridauth/", 

		"providers" => array ( 
			// https://developers.facebook.com/apps/528619360499253/
			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "528619360499253", "secret" => "39129d2f8a42788417b67b6653002b46" ),
				"scope"   => "email, user_about_me, user_birthday, user_website, read_stream, read_friendlists",
				"display" => "popup"
			),
			
			// https://dev.twitter.com/apps/2910036/settings
			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "xaUIcYQfCrPgNiU2jvPP4g", "secret" => "DuyMPEGprqfdWQj03iEAMIy84nFPZS9j1caxd4zu58" ) 
			),

			// http://hybridauth.sourceforge.net/userguide/IDProvider_info_Google.html
			"Google" => array ( 
				"enabled" => true,
				  "keys"    => array ( "id" => "1045261461287-eebsob21k9k8o93eqpc37g6ggg9g2rd1.apps.googleusercontent.com", "secret" => "at-4mvsFLm0rZJyMElQHTAFe" ), 
				  "scope"           => "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email",
				  "access_type"     => "offline",
				  "approval_prompt" => "auto"
			),

			// http://vkontakte.ru/editapp?id=3150893&section=options
			"Vkontakte" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "3150893", "secret" => "udv21vp9vp6iWImCNOXA" ) 
			),

			// http://api.mail.ru/sites/my/add
			"Mailru" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "688551", "key" => "08dbb34c39cfd00897d1b0d6fcd19d8b", "secret" => "12e9e0a380115c1305d9bc99b3c5bbc8" ) 
			),
			// http://odnoklassniki.ru/dk?st.cmd=appsInfoMyDevList&tkn=6988&st._aid=Apps_Info_MyDev
			"Odnoklassniki" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "93150976", "key" => "CBAQFOIGABABABABA", "secret" => "B51AC5FB93E2B9F180A06181" ) 
			),
			
			//////////////////////////////////////////////////////
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array ( 
				"enabled" => false 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
?>